import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base — every model module imports this one instance
    so Alembic sees a single MetaData object."""


class UUIDPkMixin:
    """UUID primary key generated by Postgres (gen_random_uuid(), built into
    core since PG13) rather than the application, so it's safe under
    concurrent inserts and doesn't leak sequential IDs."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


# ---------------------------------------------------------------------------
# Shared enums — reused across multiple table groups so a single Postgres
# ENUM type backs each concept instead of duplicating free-text columns.
# ---------------------------------------------------------------------------


class LearningLevel(str, enum.Enum):
    """Matches Phase 1 §59 — every topic supports these five levels."""

    BEGINNER = "beginner"
    PRACTICAL = "practical"
    TECHNICAL = "technical"
    ADVANCED = "advanced"
    PROFESSIONAL = "professional"


class DifficultyLevel(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
