"""fix frozen now() server defaults

Several models declared `server_default="now()"` as a bare Python string
rather than `server_default=func.now()` (a SQLAlchemy construct). When the
original migrations that created these columns were autogenerated, that
bare string got compiled into a *literal, frozen timestamp* baked into the
column's DDL default — not a dynamic call to Postgres's now() function.
Every row inserted since (that relied on the server default rather than
setting the column explicitly in Python) got the exact same fake
timestamp: whatever moment the migration happened to be generated at.

This surfaced concretely while building certificate issuance: a freshly
issued certificate's issued_at came back as a day-old timestamp instead of
"just now". Confirmed via `\\d certificates` that the live column default
was a literal `'2026-08-24 19:49:28...'::timestamptz`, not `now()`.

This migration repoints every affected column's default at the real,
dynamic `now()` function. It does not touch any existing row's stored
value — those already-wrong timestamps are historical data, not something
a schema migration should silently rewrite.

Revision ID: a119e0f1bd4b
Revises: 63ecb4f70e07
Create Date: 2026-08-25 15:12:35.083640

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a119e0f1bd4b'
down_revision: Union[str, Sequence[str], None] = '63ecb4f70e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_AFFECTED_COLUMNS = [
    ("code_submissions", "submitted_at"),
    ("ai_sessions", "started_at"),
    ("ai_messages", "created_at"),
    ("ai_embeddings", "created_at"),
    ("notifications", "created_at"),
    ("audit_logs", "created_at"),
    ("model_runs", "created_at"),
    ("project_submissions", "submitted_at"),
    ("user_roles", "granted_at"),
    ("badges", "earned_at"),
    ("certificates", "issued_at"),
]


def upgrade() -> None:
    for table, column in _AFFECTED_COLUMNS:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN {column} SET DEFAULT now()")


def downgrade() -> None:
    # No meaningful downgrade: the "previous" state was a frozen literal
    # timestamp from whenever the original migration was generated, which
    # is a bug, not a schema this migration should know how to restore.
    pass
