"""add portfolio_public to profiles

Revision ID: e57dc61899ea
Revises: e5ed8f0be2da
Create Date: 2026-08-25 15:44:54.173439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57dc61899ea'
down_revision: Union[str, Sequence[str], None] = 'e5ed8f0be2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'profiles', sa.Column('portfolio_public', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.alter_column('profiles', 'portfolio_public', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'portfolio_public')
    # ### end Alembic commands ###
