"""add interview questions table

Revision ID: e5ed8f0be2da
Revises: a119e0f1bd4b
Create Date: 2026-08-25 15:31:00.825629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e5ed8f0be2da'
down_revision: Union[str, Sequence[str], None] = 'a119e0f1bd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    learning_level_enum = postgresql.ENUM(
        'BEGINNER', 'PRACTICAL', 'TECHNICAL', 'ADVANCED', 'PROFESSIONAL', name='learning_level', create_type=False
    )
    op.create_table('interview_questions',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('difficulty', learning_level_enum, nullable=False),
    sa.Column('sample_answer', sa.Text(), nullable=False),
    sa.Column('career_path_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_career_path_id'), 'interview_questions', ['career_path_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_category'), 'interview_questions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_category'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_career_path_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
